version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=db_crud
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"